
CREATE TABLE PATIENT
(
    ID     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name text not null,
    last_name text not null,
    mid_name text,
    age number not null
);

/* 

CREATE TABLE DISEASE
(
    ID     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code text not null,
    desc text not null
)

*/