DROP TABLE IF EXISTS PATIENT;
DROP TABLE IF EXISTS DISEASE;


CREATE TABLE IF NOT EXISTS DISEASE
(
    ID     BIGINT GENERATED by default as identity,
    code text not null,
    descr text not null,
    PRIMARY KEY(ID)

    );

CREATE TABLE PATIENT
(
    ID     BIGINT GENERATED by default AS IDENTITY,

    first_name text not null,
    last_name text not null,
    mid_name text,
    age integer not null,
    diseaseId BIGINT,
    PRIMARY KEY(ID),
    CONSTRAINT fk_patient 
        FOREIGN KEY(diseaseId) references DISEASE(ID)
);
